### ISSUE TITLE
module.zip missing files

### ISSUE THREAD

**Issue by kakaroto** [League-of-Foundry-Developers/intro.js-lib#4]
Hi. the module.zip that gets generated (And which is linked by the manifest) doesn't contain all the files (missing css files) : https://github.com/League-of-Foundry-Developers/intro.js-lib/releases/tag/3.2.1-fvtt3

**Comment by arcanistzed** [comment]
I PRed a fix for this a while ago which was merged. This issue can be closed 🙂
